[package]
name = "tallyman"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"
description = "tallyman is a rust library for talling votes"
license = "MIT OR Apache-2.0"
repository = "https://github.com/phayes/tallyman"
readme = "README.md"
keywords = ["voting", "election", "tally", "stv", "condorcet"]
categories = ["science"]

[badges]
travis-ci = { repository = "https://github.com/phayes/tallyman", branch = "master" }
codecov = { repository = "https://github.com/phayes/tallyman", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["rational"]

[features]
default = []
rational = ["num-rational"]

[dependencies]
hashbrown = "0.1.6"
failure = "0.1.3"
petgraph = {default-features = false, version = "0.4.13"}
derive_more = "0.13.0"
num-traits = "0.2.6"
num-rational = {optional = true, version = "0.2.1"}

[dev-dependencies]
criterion = "0.2"
rand = "0.6.0"

[[bench]]
name = "benchmark"
harness = false