[package]
name = "tallyman"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[package.metadata.docs.rs]
features = ["rational"]

[features]
default = []
rational = ["num-rational"]

[dependencies]
hashbrown = "0.1.6"
petgraph = {default-features = false, version = "0.4.13"}
derive_more = "0.13.0"
num-traits = "0.2.6"
num-rational = {optional = true, version = "0.2.1"}

[dev-dependencies]
criterion = "0.2"
rand = "0.6.0"

[[bench]]
name = "benchmark"
harness = false